import { deleteOrgBySlug } from "./auth-test-helpers";
import { test } from "./fixtures";
import { OrgPage } from "./pages/org.page";

// ---------------------------------------------------------------------------
// Tests — Organization creation (requires running database + auth session)
// ---------------------------------------------------------------------------

test.describe("Organization flows — create org", () => {
  const orgSlug = `test-org-${Date.now()}`;
  const orgName = "Test Org";

  test("authenticated user can create an organization", async ({ authedPage }) => {
    const orgPage = new OrgPage(authedPage);
    await orgPage.goto();

    await orgPage.expectCreateFormVisible();

    // Fill organization name and verify slug auto-generates
    await orgPage.orgNameInput.fill(orgName);
    await orgPage.expectSlugAutoGenerated("test-org");

    // Override slug with unique value to avoid collisions
    await orgPage.orgSlugInput.fill(orgSlug);

    // Submit the form
    await orgPage.submitButton.click();

    // Verify redirect to dashboard
    await orgPage.expectRedirectToDashboard();

    // Clean up: delete the organization from the database
    await deleteOrgBySlug(orgSlug);
  });
});

// ---------------------------------------------------------------------------
// Tests — Accept invite (error path — invalid invitation ID)
// ---------------------------------------------------------------------------

test.describe("Organization flows — accept invite", () => {
  test("invalid invitation ID shows error state", async ({ authedPage }) => {
    const orgPage = new OrgPage(authedPage);
    await orgPage.gotoAcceptInvite("invalid-id-does-not-exist");

    // The page first shows a loading/accepting state, then transitions to error
    await orgPage.expectInviteError();
  });
});
