import { expect, type Page } from "@playwright/test";

export class OrgPage {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
  }

  // ---------------------------------------------------------------------------
  // Selectors
  // ---------------------------------------------------------------------------

  get heading() {
    return this.page.getByRole("heading", { name: "Create your organization" });
  }

  get createOrgForm() {
    return this.page.getByTestId("create-organization-form");
  }

  get orgNameInput() {
    return this.page.getByLabel("Organization name");
  }

  get orgSlugInput() {
    return this.page.getByLabel("Organization slug");
  }

  get submitButton() {
    return this.page.getByTestId("create-organization-submit");
  }

  get inviteError() {
    return this.page.getByTestId("invite-error");
  }

  get inviteErrorHeading() {
    return this.page.getByRole("heading", { name: "Unable to accept invitation" });
  }

  // ---------------------------------------------------------------------------
  // Actions
  // ---------------------------------------------------------------------------

  async goto() {
    await this.page.goto("/create-organization");
  }

  async gotoAcceptInvite(id: string) {
    await this.page.goto(`/accept-invite/${id}`);
  }

  async createOrg(name: string, slug?: string) {
    await this.orgNameInput.fill(name);
    if (slug !== undefined) {
      await this.orgSlugInput.fill(slug);
    }
    await this.submitButton.click();
  }

  // ---------------------------------------------------------------------------
  // Assertions
  // ---------------------------------------------------------------------------

  async expectCreateFormVisible() {
    await expect(this.heading).toBeVisible();
    await expect(this.createOrgForm).toBeVisible();
    await expect(this.orgNameInput).toBeVisible();
    await expect(this.orgSlugInput).toBeVisible();
    await expect(this.submitButton).toBeVisible();
  }

  async expectSlugAutoGenerated(expected: string) {
    await expect(this.orgSlugInput).toHaveValue(expected);
  }

  async expectRedirectToDashboard() {
    await expect(this.page).toHaveURL(/\/dashboard/, { timeout: 10_000 });
  }

  async expectInviteError() {
    await expect(this.inviteError).toBeVisible({ timeout: 10_000 });
    await expect(this.inviteErrorHeading).toBeVisible();
  }
}
